-- @block
CREATE TABLE STUDENT(
    ID INT PRIMARY KEY,
    EMAIL VARCHAR(50) NOT NULL,
    NAME VARCHAR(50) NOT NULL
);
-- @block
CREATE TABLE class(
    ID INT PRIMARY KEY,
    batch VARCHAR(4) NOT NULL,
    Attendence INT NOT NULL,
    FOREIGN KEY(ID) REFERENCES STUDENT(ID)
);
create TABLE Result(
    ID INT PRIMARY KEY,
    Semester int NOT NULL,
    MARKS INT NOT NULL,
    FOREIGN KEY(ID) REFERENCES STUDENT(ID)
);